LNAME = HA
LNAME = KIM
FNAME = CHULSOO

LNAME += MANSOO

NAME1 = my
NAME1 ?= string1
NAME2 ?= string2

NAME = '"KWON PARK KIM"'

A = $(B) AA
B = BB

a := $(b) aa
b := bb

all : 
	@echo $(NAME)
#	@echo A= $(A)
#	@echo a= $(a)
#	@echo LNAME= $(LNAME)
#	@echo ${LNAME}, $(FNAME)
#	@echo Mr. $(LNAME)
#	@echo NAME1= $(NAME1)
#	@echo NAME2= $(NAME2)
